-- 01_create_tables.sql

DROP SCHEMA IF EXISTS videoclub CASCADE;
CREATE SCHEMA videoclub;

SET search_path TO videoclub;

-- 1. Reference tables

CREATE TABLE document_type (
    document_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE director (
    director_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL
);

CREATE TABLE copy_status (
    copy_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

-- 2. Members

CREATE TABLE member (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_number INT NOT NULL UNIQUE,
    document_type_id INT NOT NULL,
    document_number VARCHAR(30) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name_1 VARCHAR(80) NOT NULL,
    last_name_2 VARCHAR(80),
    email VARCHAR(150),
    phone VARCHAR(20),
    birth_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_document_type
        FOREIGN KEY (document_type_id)
        REFERENCES document_type(document_type_id),
    CONSTRAINT uq_member_document
        UNIQUE (document_type_id, document_number)
);

CREATE TABLE member_address (
    member_id INT PRIMARY KEY,
    postal_code VARCHAR(10) NOT NULL,
    street VARCHAR(120) NOT NULL,
    street_number VARCHAR(10) NOT NULL,
    floor VARCHAR(10),
    letter VARCHAR(20),
    CONSTRAINT fk_member_address_member
        FOREIGN KEY (member_id)
        REFERENCES member(member_id)
        ON DELETE CASCADE
);

-- 3. Movies

CREATE TABLE movie (
    movie_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT NOT NULL,
    director_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    synopsis TEXT,
    CONSTRAINT fk_movie_genre
        FOREIGN KEY (genre_id)
        REFERENCES genre(genre_id),
    CONSTRAINT fk_movie_director
        FOREIGN KEY (director_id)
        REFERENCES director(director_id)
);

CREATE TABLE movie_copy (
    copy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id INT NOT NULL,
    copy_number INT NOT NULL,
    acquisition_date DATE,
    copy_status_id INT NOT NULL,
    CONSTRAINT fk_movie_copy_movie
        FOREIGN KEY (movie_id)
        REFERENCES movie(movie_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_movie_copy_status
        FOREIGN KEY (copy_status_id)
        REFERENCES copy_status(copy_status_id),
    CONSTRAINT uq_movie_copy
        UNIQUE (movie_id, copy_number)
);

-- 4. Rentals

CREATE TABLE rental (
    rental_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id INT NOT NULL,
    member_id INT NOT NULL,
    rental_date DATE NOT NULL,
    expected_return_date DATE,
    return_date DATE,
    CONSTRAINT fk_rental_copy
        FOREIGN KEY (copy_id)
        REFERENCES movie_copy(copy_id),
    CONSTRAINT fk_rental_member
        FOREIGN KEY (member_id)
        REFERENCES member(member_id),
    CONSTRAINT ck_expected_return_date
        CHECK (expected_return_date IS NULL OR expected_return_date >= rental_date),
    CONSTRAINT ck_return_date
        CHECK (return_date IS NULL OR return_date >= rental_date)
);

-- Prevents two active rentals for the same copy
CREATE UNIQUE INDEX uq_active_rental_per_copy
ON rental(copy_id)
WHERE return_date IS NULL;
